apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcask-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/bitcask"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcask-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
