apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcask
  template:
    metadata:
      labels:
        app: bitcask
    spec:
      initContainers:
      - name: wait-for-pvc
        image: busybox:latest
        command: ['sh', '-c', 'until ls -la /data && touch /data/test-file && rm /data/test-file; do echo "Waiting for PVC to be mounted..."; sleep 2; done; mkdir -p /data/logs /data/hints;echo "PVC is mounted and writable!"']
        volumeMounts:
        - name: bitcask-data
          mountPath: /data
      containers:
      - name: bitcask
        image: bitcask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: bitcask-data
          mountPath: /data
      volumes:
      - name: bitcask-data
        persistentVolumeClaim:
          claimName: bitcask-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcask-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: bitcask
  labels:
    app: bitcask
spec:
  type: NodePort
  selector:
    app: bitcask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: bitcask-port
---

