apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcask-normalizer
spec:
  selector:
    matchLabels:
      app: bitcask-normalizer
  template:
    metadata:
      labels:
        app: bitcask-normalizer
    spec:
      containers:
      - name: bitcask-normalizer
        image: bitcask-normalizer:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "weather-station"
        - name: BITCASK_SERVER_HOST
          value: "bitcask"
        - name: BITCASK_SERVER_PORT
          value: "5000"


