apiVersion: apps/v1
kind: Deployment
metadata:
  name: parquet-maker
spec:
  selector:
    matchLabels:
      app: parquet-maker
  template:
    metadata:
      labels:
        app: parquet-maker
    spec:
      initContainers:
      - name: init-parquet-maker
        image: busybox
        command: ['sh', '-c', 'until ls -la /app/output; do echo "Waiting for persistent storage to be ready..."; sleep 2; done; mkdir -p /app/output']
        volumeMounts:
        - name: parquet-data
          mountPath: /app/output
      containers:
      - name: parquet-maker
        image: parquet-maker:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: BOOTSTRAP_SERVER
          value: "kafka:9092"
        - name: TOPIC
          value: "weather-station"
        - name: OUTPUT_DIR
          value: "/app/output"
        - name: MAX_FILE_SIZE_MB
          value: "1"
        - name: BATCH_SIZE
          value: "10000"
        volumeMounts:
        - name: parquet-data
          mountPath: /app/output
      volumes:
      - name: parquet-data
        persistentVolumeClaim:
          claimName: parquet-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
