apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rain-detector
  template:
    metadata:
      labels:
        app: rain-detector
    spec:
      containers:
      - name: rain-detector
        image: rain-detector:latest
        imagePullPolicy: Never  
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"