apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-station
spec:
  serviceName: "weather-station"
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
      - name: weather-station
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: STATION_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: weather-station
  labels:
    app: weather-station
spec:
  clusterIP: None
  selector:
    app: weather-station