# Dockerfile for Bitcask Client
FROM eclipse-temurin:21-jre-alpine
# Set working directory
WORKDIR /app

RUN mkdir -p /app/results

# Copy the compiled classes
COPY /target/BitcaskClient-1.0-SNAPSHOT.jar /app/bitCaskClient.jar


